# Generated by Django 6.0.4 on 2026-04-18 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='书名')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN')),
                ('publisher', models.CharField(blank=True, max_length=100, verbose_name='出版社')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='出版日期')),
                ('description', models.TextField(blank=True, verbose_name='图书简介')),
                ('cover_image', models.URLField(blank=True, default='https://via.placeholder.com/150x200?text=No+Cover', verbose_name='封面图片')),
                ('total_copies', models.PositiveIntegerField(default=1, verbose_name='总库存')),
                ('available_copies', models.PositiveIntegerField(default=1, verbose_name='可借数量')),
                ('location', models.CharField(blank=True, max_length=50, verbose_name='存放位置')),
                ('status', models.CharField(choices=[('available', '可借阅'), ('borrowed', '已借出'), ('reserved', '已预约'), ('maintenance', '维护中')], default='available', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '图书分类',
                'verbose_name_plural': '图书分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(auto_now_add=True, verbose_name='借阅日期')),
                ('due_date', models.DateTimeField(verbose_name='应还日期')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='实际归还日期')),
                ('status', models.CharField(choices=[('borrowed', '借阅中'), ('returned', '已归还'), ('overdue', '已逾期')], default='borrowed', max_length=20, verbose_name='借阅状态')),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='罚款金额')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='图书')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='借阅用户')),
            ],
            options={
                'verbose_name': '借阅记录',
                'verbose_name_plural': '借阅记录',
                'ordering': ['-borrow_date'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.category', verbose_name='分类'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('max_books', models.PositiveIntegerField(default=5, verbose_name='最大借阅数量')),
                ('is_vip', models.BooleanField(default=False, verbose_name='VIP用户')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
    ]
